### ISSUE TITLE
send password

### ISSUE THREAD

**Issue by medeirosramos** [sfonteneau/AADInternals_python#8]
I am using PasswordHashSync, but i receive this error: 

AADInternals.py", line 661, in set_userpassword
    raise Exception(formatresponse.get('b:ExtendedErrorInformation',formatresponse))
Exception: {'b:CloudAnchor': {'@i:nil': 'true'}, 'b:Result': '2', 'b:SourceAnchor': '9c6fbec9-2ac9-4800-9382-0690a2cc69ea'}

Sorry for my english

**Comment by sfonteneau** [comment]
unfortunately this is the only information that Microsoft returns

This message often happens if you are too quick between creating the user and sending their password :
https://github.com/sfonteneau/AzureADConnect_Samba4/blob/main/run_sync.py#L368

At this time microsoft does not yet know the SourceAnchor, You have to give him time
